language: haxe
sudo: false
haxe:
 - development

install:
 - haxelib install hxnodejs
 - haxelib install compiletime
 - haxelib install mconsole
 - haxelib git mockatoo https://github.com/misprintt/mockatoo master src

script:
 - haxe build.hxml
